config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'welcome/index'
  resources :users, only: [:update, :show]

  resources :projects
  
  resources :projects do
    resources :documents
  end
  

  resources :documents
  #resources :documents, only:[:index, :show, :new, :edit]

  get 'welcome/about'

  root to: 'welcome#index'
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :project

  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :documents
  has_many :collaborations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :projects
  has_many :documents, dependent: :destroy

  mount_uploader :avatar, AvatarUploader
  

  def translator?
    role == 'translator'
  end

  def editor?
    role == 'editor'
  end

  def proofreader?
    role == 'proofreader'
  end

  def project_manager?
    role == 'project manager'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def after_sign_in_path_for(projects)
    projects_path(current_user)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
   @documents = Document.all
   authorize @documents
  end

  def new
    @document = Document.new
    authorize @document
  end

  def create
    @document = Document.new(document_params)
    @project = Project.find(params[:project_id])
    @document.project = @project
    if @document.save
      redirect_to @project, notice: "The document #{@document.name} has been uploaded."
    else
      render "new"
    end
  end

  def show
    #/projects/:project_id/documents/:id
    @project = Project.find(params[:project_id])
    @document = Document.find(params[:id])
    authorize @project
  end


 

  def edit
    @document = Document.find(params[:id])
    authorize @document
  end

  def update
    @document = Document.find(params[:id])
    authorize @document

    if @document.update_attributes(params.require(:document).permit(:name, :attachment, :description))
      redirect_to @document
    else
      flash[:error] = "Error saving document. Please try again."
      render :edit
  end

end

def destroy
    @project = Project.find(params[:project_id])
    @document = Document.find(params[:id])
    

    if @document.destroy 
      flash[:notice] =  "\"#{@document.name}\" was deleted successfully."
      redirect_to @project

    else flash[:error] = "There was an error deleting the document."
      render :show
    
    end
  end


private
  def document_params
    params.require(:document).permit(:name, :attachment, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    authorize @projects
  end

  def new
    @project = Project.new
    authorize @project
  end

  def show
    @project = Project.find(params[:id])
    @documents = @project.documents
    authorize @project
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.find(params[:id])
    authorize @project

    if @project.update_attributes(params.require(:project).permit(:name, :description))
      redirect_to @project
    else
      flash[:error] = "Error saving topic. Please try again."
      render :edit
  end

end

  def create
    @project = Project.new(project_params)
    #@project.user = current_user
    #authorize @project

    if @project.save
      redirect_to projects_path, notice: "The project #{@project.name} has been uploaded."
    else
      render "new"
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: "The project #{@project.name} has been deleted."
  end
  

  private
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, except: [:show]

  def show
    @user = current_user
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end

  end

  private

  def user_params
   params.require(:user).permit(:name, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
      end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.erb
<%= form_for [project, document], multipart:true do |f| %>
  <% if document.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(document.errors.count, "error") %>.</h4>
      <ul>
        <% document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(document.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter document title" %>
  <% end %>
  <%= form_group_tag(document.errors[:attachment]) do %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
  <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Documents#edit</h1>
<p>Find me in app/views/documents/edit.html.erb</p>

app/views/documents/index.html.erb
<h1>Documents#index</h1>
<p>Find me in app/views/documents/index.html.erb</p>

app/views/documents/new.html.erb
<% if !@document.errors.empty? %>
  <div class = "alert alert-error">

    <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>

  </div>
<% end %>

<div class = "well">
  <%= form_for @document, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

<h4>Add translation:</h4>
<%= form_for [@project, Document.new], remote: true do |f| %>

<div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control' %>
</div>
<%= f.submit "Save translation", class: 'btn btn-success' %>
<% end %>

app/views/documents/show.html.erb
<h2><%= document.name %></h2>

<% if !@document.errors.empty? %>
  <div class = "alert alert-error">

    <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>

  </div>
<% end %>

<div class = "well">
  <%= form_for @document, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transportal</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

  <ul class="nav nav-tabs">
    <li><%= link_to "Home", welcome_index_path %></li>
      <% if policy(Project.new).create? %>
     <li><%= link_to "Projects", projects_path %></li>
      <% end %>
    <div class="pull-right user-info">
      <% if current_user %>
      <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
      Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! 

      <%= link_to "Sign out",destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

    <%= yield %>
  </div>
  
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for projects do |f| %>
  <% if project.errors.any? %>
  <div class="alert alert-danger">
    <h4>There are <%= pluralize(project.errors.count, "error") %>.</h4>
    <ul>
      <% project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_group_tag(project.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter project title" %>
    <% end %>
    <%= form_group_tag(project.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter translation body text" %>
    <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    <% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/index.html.erb
<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<br />

 <% if policy(Project.new).create? %>
<%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
<% end %>

<br />
<br />



<table class = "table table-bordered table-striped">
  <thread>
    <tr>
      <th>Project Name</th>
    </tr>
  </thread>
 
  <tbody>
    <% @projects.each do |project| %>

    <tr>
      <td><%= link_to project.name, project_path(project) %></td>
      <td><%= button_to "Delete", project_path(project), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{project.name}?" %> </td>
    </tr>
    
  <% end %>
</tbody>
</table>

app/views/projects/new.html.erb
<% if !@project.errors.empty? %>
  <div class = "alert alert-error">

    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>

  </div>
<% end %>

<div class = "well">
  <%= form_for @project, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%#= f.label :attachment %>
    <%#= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<table class = "table table-bordered table-striped">
  <thread>
    <tr>
      <th>File Name</th>
      
        <th>Download Attachment</th>
        <th> </th>
      
    </tr>
  </thread>

<tbody>
    <% @documents.each do |document| %>

    <tr>
      <td><%= link_to document.name, new_document_path(@document) %></td>
      
      <td><%= link_to "Download Attachment", document.attachment_url %></td>
      <td><%= button_to "Delete", [@project, document], method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{document.name}?" %></td>
    </tr>
    
  <% end %>
</tbody>

</table>

<%= render partial: 'documents/form', locals: {document: Document.new, project: @project} %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>About Transportal</h1>
<p>Created by: Virginia Cooper </p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Transportal</h1>
  <p> Transportal is a translator's resource for project collaboration.</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Create translator profile</h2>
    <p>Transportal allows translators to create profiles for collaboration.</p>
  </div>

  <div class="col-md-4">
    <h2>Create terminology forum</h2>
    <p>Transportal allows translators to post and comment on terminology topics.</p>
  </div>

  <div class="col-md-4">
    <h2>Create translation wikis</h2>
    <p>Transportal allows users to create translation wikis.</p>
  </div>
</div>